### ISSUE TITLE
YAML formatting for variables in docs broken.

### ISSUE THREAD

**Issue by GrahamDumpleton** [eduk8s/eduk8s-docs#17]
Formatting for name/values variable pairs in docs at:

* https://docs.edukates.io/en/develop/workshop-content/workshop-instructions.html?highlight=config#adding-custom-data-variables

is broken.

For example, should be:

```
config:
    vars:
    - name: LANGUAGE
      value: undefined
```

Occurs in multiple places.
